services:
  gochain:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5443:5443"
      - "6443:6443"
    environment:
      - PEERS=""
    networks:
      - gochain

networks:
    gochain:
      driver: bridge