definitions:
  app.BalanceResponse:
    properties:
      message:
        type: string
    type: object
  app.BlockRequestDto:
    properties:
      data:
        type: string
    type: object
  app.BlockResponseDto:
    properties:
      data:
        type: string
      difficulty:
        type: integer
      hash:
        type: string
      last_hash:
        type: string
      nonce:
        type: integer
      timestamp:
        type: string
    type: object
  app.BlockchainDto:
    properties:
      chain:
        type: string
    type: object
  app.WalletDto:
    properties:
      address:
        type: string
    type: object
  domain.Input:
    properties:
      address:
        type: string
      amount:
        type: number
      signature:
        type: string
      timestamp:
        type: string
    type: object
  domain.Transaction:
    properties:
      amount:
        type: number
      id:
        type: string
      input:
        $ref: '#/definitions/domain.Input'
      output:
        additionalProperties:
          $ref: '#/definitions/domain.Input'
        type: object
    type: object
info:
  contact: {}
paths:
  /balance:
    get:
      description: Retrieves the balance of a wallet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.BalanceResponse'
            type: array
      summary: Get balance
      tags:
      - balance
  /blocks:
    get:
      description: Gets the blockchain
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.BlockchainDto'
      summary: Gets the blockchain
      tags:
      - blocks
  /mine:
    post:
      consumes:
      - application/json
      description: Mines a new block and adds it to the blockchain
      parameters:
      - description: Block Request Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.BlockRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.BlockResponseDto'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Mine a block
      tags:
      - mine
  /public-key:
    get:
      description: Retrieves the address of a wallet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.WalletDto'
      summary: Get balance
      tags:
      - public-key
  /transactions:
    get:
      description: Gets transactions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Transaction'
            type: array
      summary: Gets transactions
      tags:
      - transactions
    post:
      description: Creates a transaction in the pool
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Transaction'
            type: array
      summary: Create transaction
      tags:
      - transactions
swagger: "2.0"
